name         'chrisboulton-postfix'
version      '0.0.2'
license      'MIT'
summary      'Install and manage Postfix'
description  'Install and manage a Postfix based mail server'
author       'Chris Boulton <chris@chrisboulton.com>'
source       'https://github.com/chrisboulton/puppet-postfix'
project_page 'https://github.com/chrisboulton/puppet-postfix'
dependency   'puppetlabs/stdlib', '> 0.0.0'